// GENERATED by `bash build.sh website` -- do not edit by hand.
// Single source: tex-artefacts/version.tex (\TFPTversion) + git commit count.
export const SITE_VERSION = "5.3";
export const SITE_REV = "295";
export const SITE_DATE = "2026-06-24";
