// GENERATED by `bash build.sh website` -- do not edit by hand.
// Single source: tex-artefacts/version.tex (\TFPTversion) + git commit count.
export const SITE_VERSION = "5.2";
export const SITE_REV = "207";
export const SITE_DATE = "2026-06-18";
